### ISSUE TITLE
Awesome idea, if possible please provide video or gif to show the usability

### ISSUE THREAD

**Issue by developmentkw** [IIAmir/local_rembg#1]

**Comment by IIAmir** [comment]
Thanks! If you'd like an example code to understand how to use this library, you can check out the [Example Project](https://github.com/IIAmir/local_rembg/blob/main/example/lib/main.dart).

Additionally, if you're interested in seeing the output result on iOS:

# Before:

<img src="https://fastupload.io/secure/file/Z9dzBkoR5Gk1b"/>

# After:

<img src="https://fastupload.io/secure/file/RMKGJXLqL31oP"/>
