### ISSUE TITLE
BG  not remove on iOS Simulator

### ISSUE THREAD

**Issue by Milan-Verselix** [IIAmir/local_rembg#2]
I running this feature on iOS simulator with 17.0 iOS version but it's not working...

I getting this error...
{message: Unable to process image, status: 0}

It's working fine on iOS real device.

**Comment by IIAmir** [comment]
I am not entirely sure why it does not function in the simulator; perhaps this is due to the absence of a real GPU.

**Comment by Milan-Verselix** [comment]
OK, I think it's valid reason...
