### ISSUE TITLE
Issue: getting crash on the android

### ISSUE THREAD

**Issue by ShivamS1234** [IIAmir/local_rembg#7]
E/AndroidRuntime(13794): FATAL EXCEPTION: DefaultDispatcher-worker-3
E/AndroidRuntime(13794): Process: com.gulfbank.GBK.uat, PID: 13794
E/AndroidRuntime(13794): java.lang.IllegalArgumentException: width must be > 0
E/AndroidRuntime(13794): 	at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:445)
E/AndroidRuntime(13794): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
E/AndroidRuntime(13794): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:862)
E/AndroidRuntime(13794): 	at com.example.local_rembg.LocalRembgPlugin.cropImage(LocalRembgPlugin.kt:180)
E/AndroidRuntime(13794): 	at com.example.local_rembg.LocalRembgPlugin.access$cropImage(LocalRembgPlugin.kt:23)
E/AndroidRuntime(13794): 	at com.example.local_rembg.LocalRembgPlugin$processSegmentationMask$1.invokeSuspend(LocalRembgPlugin.kt:123)
E/AndroidRuntime(13794): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(13794): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
E/AndroidRuntime(13794): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
E/AndroidRuntime(13794): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
E/AndroidRuntime(13794): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
E/AndroidRuntime(13794): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
E/AndroidRuntime(13794): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
E/AndroidRuntime(13794): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
E/AndroidRuntime(13794): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cb4a385, Dispatchers.IO]
I/Process (13794): Sending signal. PID: 13794 SIG: 9
D/SessionLifecycleClient(13794): Sending lifecycle 2 to service

**Comment by IIAmir** [comment]
Thank you for your feedback! The newer version is now available for use.
